### ISSUE TITLE
xblock installation breaks ironwood installation.

### ISSUE THREAD

**Issue by sumeshiit** [Stanford-Online/xblock-in-video-quiz#27]
Hi all,

we are trying to setup a open edx platform (ironwood). when we restarted the server after installing the quiz in video xblock. the openedx webpage showing error message like " Uh oh, we are having some server issues…" with a sinking ship image. we tried to restart server and lms & cms multiple times. but there is no change.

lms & cms status shows RUNNING and if fails with uptime 0:00:01 or uptime 0:00:02. We uninstalled the xblock and  restarted server. But no change in server status, it still fails. Anyone please help to resolve this issue.

Logs are:

```
==> lms_high_1-stderr.log <==
    self._wrapped = Settings(settings_module)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/conf/__init__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/edx/app/edxapp/edx-platform/lms/envs/production.py", line 31, in <module>
    from .common import *
  File "/edx/app/edxapp/edx-platform/lms/envs/common.py", line 847, in <module>
    from xmodule.x_module import XModuleMixin
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/x_module.py", line 38, in <module>
    from opaque_keys.edx.asides import AsideUsageKeyV2, AsideDefinitionKeyV2
ImportError: cannot import name AsideUsageKeyV2

==> lms_default_1-stderr.log <==
Traceback (most recent call last):
  File "/edx/app/edxapp/edx-platform/manage.py", line 119, in <module>
    startup = importlib.import_module(edx_args.startup)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/edx/app/edxapp/edx-platform/lms/startup.py", line 9, in <module>
    settings.INSTALLED_APPS  # pylint: disable=pointless-statement
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/conf/__init__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/edx/app/edxapp/edx-platform/lms/envs/production.py", line 31, in <module>
    from .common import *
  File "/edx/app/edxapp/edx-platform/lms/envs/common.py", line 847, in <module>
    from xmodule.x_module import XModuleMixin
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/x_module.py", line 38, in <module>
    from opaque_keys.edx.asides import AsideUsageKeyV2, AsideDefinitionKeyV2
ImportError: cannot import name AsideUsageKeyV2

==> cms_high_1-stderr.log <==
    __import__(name)
  File "/edx/app/edxapp/edx-platform/cms/startup.py", line 9, in <module>
    settings.INSTALLED_APPS  # pylint: disable=pointless-statement
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/conf/__init__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/edx/app/edxapp/edx-platform/cms/envs/production.py", line 17, in <module>
    from .common import *
  File "/edx/app/edxapp/edx-platform/cms/envs/common.py", line 49, in <module>
    import lms.envs.common
  File "/edx/app/edxapp/edx-platform/lms/envs/common.py", line 847, in <module>
    from xmodule.x_module import XModuleMixin
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/x_module.py", line 38, in <module>
    from opaque_keys.edx.asides import AsideUsageKeyV2, AsideDefinitionKeyV2
ImportError: cannot import name AsideUsageKeyV2


==> cms_default_1-stderr.log <==
  File "/edx/app/edxapp/edx-platform/cms/envs/common.py", line 49, in <module>
    import lms.envs.common
  File "/edx/app/edxapp/edx-platform/lms/envs/common.py", line 847, in <module>
    from xmodule.x_module import XModuleMixin
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/x_module.py", line 38, in <module>
    from opaque_keys.edx.asides import AsideUsageKeyV2, AsideDefinitionKeyV2
ImportError: cannot import name AsideUsageKeyV2
```

**Comment by iamsumesh** [comment]
This issue is solved after installing edx-opaque-keys==0.4.4
